config/routes.rb
Rails.application.routes.draw do

  get "monit/ammount_contrib"
  get "monit/ammount_contrib"
  get "monit/ammount_per_service"
  get "monit/reduction_percentual"
  get "monit/total_keeped"
  get "monit/biggest_dealers"

  root 'monit#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout 'yeti'
end

app/controllers/monit_controller.rb
class MonitController < ApplicationController

  before_action :get_categories, only: [:ammount_contrib,
                                        :ammount_per_service,
                                        :reduction_percentual,
                                        :total_keeped ]

  def index
  end

  def ammount_contrib
    gon.series = [{
      name: 'Contribuintes Atendidos',
      data: [49, 71, 106, 129, 454],
      dataLabels: get_datalabel_config,
      color: '#008783'
    }]
  end

  def ammount_per_service
    gon.series     = [
      { name: 'Dívida Ativa - SEFIN', data: [49.9, 71.5, 106.4, 129.2], dataLabels: get_datalabel_config },
      { name: 'Dívida Ativa - PGM',   data: [83.6, 78.8, 98.5, 93.4]  , dataLabels: get_datalabel_config },
      { name: 'Cadastro ISS',         data: [48.9, 38.8, 39.3, 41.4]  , dataLabels: get_datalabel_config },
      { name: 'Cadastro IPTU',        data: [42.4, 33.2, 34.5, 39.7]  , dataLabels: get_datalabel_config }
    ]
  end

  def reduction_percentual
    gon.series = [{
      name: I18n.t("chart.reduction_percentual"),
      data: [49, 71, 106, 129, 454],
      dataLabels: get_datalabel_config,
      color: '#008783'
    }]
  end

  def total_keeped
    gon.series = [{

    }]
  end

  def biggest_dealers
  end

  private

  def get_categories
    gon.categories = [ '13/08 ', '14/08', '15/08', '16/08', 'Total' ]
  end

  def get_datalabel_config
    data = {
      dataLabels: {
          enabled: true,
          rotation: 0,
          color: '#000000',
          backgroundColor: '#FFFFFF',
          align: 'center',
          x: 4,
          y: 0,
          style: {
            fontSize: '12px',
            fontFamily: 'Verdana, sans-serif'
          }
      }
    }
    data[:dataLabels]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monit_helper.rb
module MonitHelper
end

app/views/layouts/_chart_layout.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">
        <i class="fa fa-pie-chart"></i>
        <%= chart_name %>
        </h3>
      </div>
      <div class="panel-body">
        <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<%= stylesheet_link_tag "yeti", :media => "all" %>
<%= stylesheet_link_tag "general" %>
<%= javascript_include_tag "yeti" %>
<%= Gon::Base.render_data %>
<%= yield(:page_javascript) if content_for?(:page_javascript) %>
<%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path , class: "navbar-brand" do %>
        <%= image_tag "logo.png", class: "logo" %>
      <% end %>
      <%= link_to "Mutirão Fiscal 2015", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to  t("menu.ammount_contrib"), monit_ammount_contrib_path %>
        </li>
        <li>
          <%= link_to  t("menu.ammount_per_service"), monit_ammount_per_service_path %>
        </li>
        <li>
          <%= link_to  t("menu.reduction_percentual"), monit_reduction_percentual_path %>
        </li>
        <li>
          <%= link_to  t("menu.total_keeped"), monit_total_keeped_path %>
        </li>
        <li>
          <%= link_to  t("menu.biggest_dealers"), monit_biggest_dealers_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_table_biggest_dealers.html.erb
_table_biggest_dealers.html.erb

app/views/layouts/yeti.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "pgm_monit" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= render partial: "layouts/head" %>

  </head>
  <body>
    <%= render partial: "layouts/menu" %>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/monit/ammount_contrib.html.erb
<%= render partial: "layouts/chart_layout", locals: { chart_name: t("chart.ammount_contrib") } %>

<script type="text/javascript">
  $(function () {
      $('#container').highcharts({
          chart: {
              type: 'column'
          },
          title: {
              text: ''
          },
          subtitle: {
              text: ''
          },
          xAxis: {
              categories: [
                  '13/08 ',
                  '14/08',
                  '15/08',
                  '16/08',
                  'Total'
              ],
              crosshair: true
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Quantidade'
              }
          },
          tooltip: {
              headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                  '<td style="padding:0"><b>{point.y:.1f} atendimentos</b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
          },
          plotOptions: {
              column: {
                  pointPadding: 0.2,
                  borderWidth: 0
              }
          },
          series: gon.series
      });
  });
</script>

app/views/monit/ammount_per_service.html.erb
<%= render partial: "layouts/chart_layout", locals: { chart_name: t("chart.ammount_per_service") } %>

<script type="text/javascript">
  $(function () {
      $('#container').highcharts({
          chart: {
              type: 'column'
          },
          title: {
              text: ''
          },
          subtitle: {
              text: ''
          },
          xAxis: {
              categories: gon.categories,
              crosshair: true
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Quantidade'
              }
          },
          plotOptions: {
              column: {
                  pointPadding: 0.2,
                  borderWidth: 0
              }
          },
          series: gon.series
      });
  });
</script>

app/views/monit/biggest_dealers.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">
        <i class="fa fa-pie-chart"></i>
        <%= t("chart.biggest_dealers") %>
        </h3>
      </div>
      <div class="panel-body">
        <table class="table table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>Nome</th>
              <th>Tipo pgto</th>
              <th>Origem</th>
              <th>Valor</th>
            </tr>
          </thead>
          <tbody>
            <% (1..10).each do |row| %>
              <tr>
                <th scope="row"><%= row %></th>
                <td><%= ["Joefrey Nixxon", "IPS", "Top Secret"].sample %></td>
                <td><%= ["A vista", "Parcelado"].sample %></td>
                <td><%= ["SEFIN", "PGM"].sample %></td>
                <td><%= number_to_currency rand(1000..1000000) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/monit/index.html.erb
<div class="jumbotron">
  <h1><%= t("index.text1") %></h1>
  <p><%= t("index.text2") %></p>
</div>

app/views/monit/reduction_percentual.html.erb
<%= render partial: "layouts/chart_layout", locals: { chart_name: t("chart.reduction_percentual") } %>

<script type="text/javascript">
  $(function () {
      $('#container').highcharts({
          chart: {
              type: 'column'
          },
          title: {
              text: ''
          },
          subtitle: {
              text: ''
          },
          xAxis: {
              categories: gon.categories,
              crosshair: true
          },
          yAxis: {
              min: 0,
              title: {
                  text: 'Quantidade'
              }
          },
          tooltip: {
              headerFormat: '<span style="font-size:14px">{point.key}</span><table>',
              pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                  '<td style="padding:0"><b>{point.y:.1f} atendimentos</b></td></tr>',
              footerFormat: '</table>',
              shared: true,
              useHTML: true
          },
          plotOptions: {
              column: {
                  pointPadding: 0.2,
                  borderWidth: 0
              }
          },
          series: gon.series
      });
  });
</script>

app/views/monit/total_keeped.html.erb
<%= render partial: "layouts/chart_layout", locals: { chart_name: t("chart.total_keeped") } %>

<script type="text/javascript">
  $(function () {
      $('#container').highcharts({

          chart: {
              type: 'column'
          },

          title: {
              text: ''
          },

          xAxis: {
              categories: gon.categories
          },

          yAxis: {
              allowDecimals: false,
              min: 0,
              title: {
                  text: 'Quantidade'
              }
          },

          tooltip: {
              formatter: function () {
                  return '<b>' + this.x + '</b><br/>' +
                      this.series.name + ': ' + this.y + '<br/>' +
                      'Total: ' + this.point.stackTotal;
              }
          },

          plotOptions: {
              column: {
                  stacking: 'normal'
              }
          },

          series: [{
              name: 'A Vista (SEFIN)',
              data: [5, 3, 4, 7, 2],
              stack: 'male'
          }, {
              name: 'Parcelado (SEFIN)',
              data: [3, 4, 4, 2, 5],
              stack: 'male'
          }, {
              name: 'A Vista (PGM)',
              data: [2, 5, 6, 2, 1],
              stack: 'female'
          }, {
              name: 'Parcelado (PGM)',
              data: [3, 0, 4, 4, 3],
              stack: 'female'
          }]
      });
  });
</script>